export default function About() {
    return(
        <>
            <p className="block w-1/2 mx-auto text-center">
                Quisque ac malesuada lacus. Mauris vel imperdiet elit, et semper velit. Nam aliquet ac mi quis laoreet. Quisque cursus semper dignissim. Maecenas nec accumsan nisl, a suscipit libero. Sed vel felis mollis, egestas tellus vel, viverra est. Donec euismod lectus ac purus sagittis, sed faucibus felis facilisis. Suspendisse potenti. Nunc eget massa neque.
                Donec id erat vel justo congue interdum. Donec interdum non sapien ac finibus. Suspendisse potenti. Donec laoreet varius faucibus. Quisque efficitur felis sit amet euismod vehicula. Ut faucibus porttitor enim, sed scelerisque neque. Etiam iaculis, risus ac malesuada hendrerit, eros arcu pulvinar magna, pharetra venenatis tellus orci eget odio. Integer sed rhoncus dui. Donec ornare ex felis, non convallis dui sodales id. Vestibulum interdum ex justo, consectetur vehicula felis facilisis sed.
                Vivamus tincidunt convallis mauris, sed tincidunt mi accumsan nec. Nulla felis ex, pharetra at commodo sed, tristique eget felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque sit amet tellus at tellus ultricies volutpat at ut tellus. Sed id pulvinar dolor. Nunc varius rutrum odio, non ullamcorper magna. Sed facilisis eros varius euismod consequat. Maecenas condimentum, neque vel pharetra aliquet, diam lacus viverra metus, quis varius ante metus ac odio. Etiam sagittis sapien eu accumsan rutrum. Aliquam erat volutpat. Sed suscipit nunc nec erat cursus commodo. Praesent ut metus est.
                Pellentesque rhoncus, lectus tristique maximus aliquam, orci ex convallis justo, sed congue diam dui ac massa. Sed vehicula ipsum efficitur est bibendum convallis. Aenean suscipit odio sit amet metus placerat laoreet. Fusce ac vehicula lorem. Proin eleifend imperdiet odio ac volutpat. Duis placerat nisl libero, quis commodo turpis convallis ut. Donec eget orci augue. Praesent eleifend tellus ex, id volutpat odio eleifend ac. Sed pulvinar pretium faucibus. Ut et condimentum lorem. Suspendisse et fermentum diam.
                Maecenas scelerisque venenatis odio ac facilisis. Praesent ut magna viverra, interdum ligula in, iaculis est. Vestibulum at fermentum justo. Suspendisse nec eros euismod, varius sapien eu, imperdiet velit. Morbi tristique fermentum sem. Donec condimentum scelerisque arcu, ut scelerisque tellus sodales sed. Fusce neque lacus, aliquet vel tempus eu, rhoncus ut felis. Cras lectus ipsum, rhoncus vitae pellentesque in, imperdiet sit amet erat. Fusce convallis lectus ac risus placerat commodo. Mauris non metus vitae risus gravida commodo efficitur vitae sem. Nullam vehicula ligula nec nulla pretium, imperdiet fermentum tellus blandit. Maecenas egestas pretium diam, vel rutrum magna ultrices feugiat. Phasellus sed eleifend magna, ac volutpat sem.
                Ut sagittis turpis tellus, eget dapibus erat tincidunt at. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed eleifend urna sit amet lacinia imperdiet. Aliquam vel erat a sapien maximus hendrerit eget eu tellus. Sed magna justo, accumsan non ipsum sed, sagittis consequat purus. Nullam in porta tortor, ac hendrerit libero. In hac habitasse platea dictumst. Praesent sit amet enim ligula. Integer pharetra mauris nulla, et suscipit nisi hendrerit tempus. Vivamus vitae sodales sapien. Fusce vitae turpis varius ligula vulputate interdum in ac massa. Duis est neque, elementum at elit ut, porta gravida sem.
                Quisque lobortis augue diam, volutpat aliquam enim cursus vitae. Maecenas sed dolor in tellus gravida cursus at in neque. Integer bibendum eros pretium, convallis risus a, accumsan libero. Donec nec laoreet diam. Nam sed posuere nulla, a suscipit enim. Curabitur blandit metus sit amet rutrum molestie. Integer vel sodales lorem, sit amet tristique elit. Morbi volutpat eros at tristique sollicitudin.
            </p>
        </>
    )
}